version: "3.8"
services:
  events-split:
    build: .
    environment:
      APP_NAME: events-split
      INPUT_DATA_PATH: /data-input
      OUTPUT_DATA_PATH_PREFIX: /data-output
      SPARK_PROPERTIES: |-
        spark.master=local[2]
        spark.driver.memory=2g
        spark.driver.maxResultSize=1g
    volumes:
        - /tmp:/mnt
        - ${PWD}/data-input:/data-input/
        - ${PWD}/data-output:/data-output/

  next-week-conversion-rate:
    build: .
    environment:
      PYTHON_FILE: /workspace/jobs/next_week_conversion_rate.py
      APP_NAME: next-week-conversion-rate
      USER_REGISTRATION_DATA_PATH: /data-output/user_registration
      APP_LOADED_DATA_PATH: /data-output/app_loaded
      SPARK_PROPERTIES: |-
        spark.master=local[2]
        spark.driver.memory=2g
        spark.driver.maxResultSize=1g
    volumes:
        - /tmp:/mnt
        - ${PWD}/data-output:/data-output/

  unit_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
        - .:/mnt
    entrypoint:  ["pytest", "/mnt/jobs/tests/"]

  jupyter:
    #code scatch pad
    image: jupyter/pyspark-notebook:spark-3.3.1
    working_dir: /home/jovyan/work
    volumes:
      - ${PWD}/jupyter-notebook:/home/jovyan/work
      - ${PWD}/data-input:/home/jovyan/work/data-input/
      - ${PWD}/data-output:/home/jovyan/work/data-output/
    ports:
      - "8888:8888"
