# https://taskfile.dev

version: '2'

env:
  DOCKER_IMAGE: user-registrations-and-app-loaded
  DOCKER_REGISTRY: '{{default "mrmuggymuggy" .DOCKER_REGISTRY}}'
  NAMESPACE: '{{default "default" .NAMESPACE}}'
  VERSION: 0.1.0

tasks:

  lint:
    cmds:
      - pylint --exit-zero jobs

  format:
    cmds:
      - pip install pre-commit
      - pre-commit install
      - pre-commit run --all-files

  jupyter:
    summary: |
      Local development with jupyter-notebook, fast feedback MVP
    cmds:
      #jupyter with latest spark
      - docker-compose up --abort-on-container-exit --no-log-prefix jupyter

  events-split:
    summary: |
      Run the app locally with docker-compose
    cmds:
      - docker-compose up --abort-on-container-exit --build --no-log-prefix events-split

  next-week-conversion-rate:
    summary: |
      Run the app locally with docker-compose
    cmds:
      - docker-compose up --abort-on-container-exit --build --no-log-prefix next-week-conversion-rate

  unit-tests:
    summary: |
      Run the unit-tests locally with docker-compose
    cmds:
      - docker-compose up --abort-on-container-exit --build --no-log-prefix unit_tests


  default:
    cmds:
      - echo 'try task local.run'
    silent: true
