# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Job 1: Runs all static code analysis (formatting and linting)
  static-checks:
    name: Static Checks Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Go Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run format check task
        run: task format

  # Job 2: Runs unit tests using Docker Compose
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run unit tests task
        run: task unit-tests
